version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_USER: phaneendra
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: mysqldb
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
