import { type NextPage } from "next";
import Head from "next/head";
import Mainfeed from "~/components/mainfeed/Mainfeed";
import Genresuggs from "~/components/mainfeed/genresuggestions";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-col justify-center">
        <div className="w-full ">{/* <Genresuggs /> */}</div>
        <div className="w-full ">
          <Mainfeed />
        </div>
      </main>
    </>
  );
};

export default Home;
